spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MoviesRating?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: update
      show-sql: true