

spring:
  datasource:
    url: jdbc:mysql://movie-rating-db.cpyxtwfcq2ua.us-east-1.rds.amazonaws.com:3306/MoviesRating?createDatabaseIfNotExist=true
    username: root
    password: FYaoOdtVTzNci7Fn7rEi
  jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: update
      show-sql: true
server:
  port: 8085
